### ISSUE TITLE
App

### ISSUE THREAD

**Issue by S0c5** [S0c5/contact-manager-app#19]
## Description

As a customer I want to have an basic app to manage my contacts

## Features

this app should: 

- [ ] allow me to list the contacts
- [ ] allow me to create a new contact
- [ ] read the information of one contact
