### ISSUE TITLE
Version-02

### ISSUE THREAD

**Issue by S0c5** [S0c5/contact-manager-app#23]
- [ ] As a customer I want to update a contact.
- [ ] As a customer I want to send a email when I create a new contact.
- [ ] As a customer I want to launch a rocket when I add a new contact image (🚀). (proposal)
